# power_saif_one.tcl — per-config, per-benchmark SAIF-based power report.
# Usage (batch mode, matches the -tclargs pattern already used in this project):
#   vivado -mode batch -source power_saif_one.tcl -tclargs <cfg_name> <bench_name>
#
# Assumes post_route.dcp for <cfg_name> already exists from the Track 1 run
# (C:/Users/krss/Desktop/vivado_reports/<cfg_name>/post_route.dcp) and that
# <cfg_name>_<bench_name>.saif has already been generated by xsim and copied
# into the same directory.

set cfg        [lindex $argv 0]
set saif_file  [lindex $argv 1]
set report_out [lindex $argv 2]
set base       "C:/Users/krss/Desktop/vivado_reports/$cfg"

open_checkpoint "$base/post_route.dcp"

if {![file exists $saif_file]} {
    puts "ERROR: SAIF file not found: $saif_file"
    puts "Did xsim actually run for this cfg/bench combination, and was the .saif copied here?"
    exit 1
}

read_saif -strip_path tb_saif/dut $saif_file
report_power -file $report_out

puts "Done: $report_out (from $saif_file)"

